steps:
  # Build and deploy frontend
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'frontend'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'frontend'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'app', 'deploy', 'frontend/app.yaml', '--quiet']
  
  # Install Python dependencies and deploy backend
  - name: 'python:3.9'
    args: ['pip', 'install', '-r', 'backend/requirements.txt']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'app', 'deploy', 'backend/app.yaml', '--quiet']
  
  # Deploy dispatch configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'app', 'deploy', 'dispatch.yaml', '--quiet'] 